### ISSUE TITLE
Den Folder "frontend" zu "Frontend" umbenennen

### ISSUE THREAD

**Issue by TheRealPayPaul** [TheRealPayPaul/ChatHappens#6]
Der "frontend" Ordner sollte mit einem Großbuchstaben anfangen, da alle anderen Ordner im Root ebenfalls mit einem Großbuchstaben beginnen.

**Comment by mr-tobi** [comment]
Dann würde ich alle Ordner klein schreiben, da wir auch alle Ordner in den Projekten (frontend/backend) klein geschrieben haben

**Comment by TheRealPayPaul** [comment]
Das heißt "Backend" zu "backend" und "Database" zu "database"

**Comment by mr-tobi** [comment]
ja genau
